---
# Role configuration tasks

- name: Check install log file
  stat:
    path: "{{ mysql_install_log_path }}"
  register: check_install_log_result

- name: Gather temporary password
  shell: >-
    set -o pipefail ; \
    grep 'temporary password' \
    {{ mysql_install_log_path }} \
    | awk '{ print $NF }'
  args:
    warn: no
  when: check_install_log_result.stat.exists
  changed_when: no
  register: mysql_gather_password_result
  no_log: "{{ mysql_no_log | default(true) }}"

- name: Set new password
  expect:
    command: >-
      mysql -e
      "
      ALTER USER 'root'@'localhost'
      IDENTIFIED WITH mysql_native_password
      BY '{{ mysql_root_password }}';
      "
      --connect-expired-password
      -uroot
      -p
    responses:
     "Enter password": "{{ mysql_gather_password_result.stdout }}"
  when:
    - mysql_gather_password_result is not skipped
    - mysql_gather_password_result.stdout | length > 0
  no_log: "{{ mysql_no_log | default(true) }}"
  environment:
    LANG: en_US

- name: Setup root user autologin
  expect:
     command: >-
       mysql_config_editor set --user="{{ mysql_root_user }}" --password
     responses:
       "Enter password": "{{ mysql_root_password }}"
     creates: "{{ mysql_user_autologin_file }}"
  when: mysql_create_user_autologin
  no_log: "{{ mysql_no_log | default(true) }}"

- name: Setup logrotate
  template:
    src: logrotate.j2
    dest: "{{ mysql_logrotate_config_path }}"
  when:
    - mysql_logrotate_config_path | default("") | length > 0
    - mysql_logrotate_config | default("") | length > 0

- name: Secure root accounts
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    host: "{{ mysql_host_allowed }}"
  loop: "{{ mysql_root_allowed_hosts }}"
  loop_control:
    loop_var: mysql_host_allowed
  no_log: "{{ mysql_no_log | default(true) }}"

- name: Delete all anonymous users
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    user: ""
    host_all: yes
    state: absent
  no_log: "{{ mysql_no_log | default(true) }}"

- name: Setup backup user
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    user: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_password }}"
    priv: "{{ lookup('template', 'privileges.yml.j2') }}"
  when: mysql_backup_user is defined
  no_log: "{{ mysql_no_log | default(true) }}"
  vars:
    mysql_privileges_dict: "{{ mysql_backup_privileges }}"

- name: Remove test database
  mysql_db:
   login_user: "{{ mysql_root_user }}"
   login_password: "{{ mysql_root_password }}"
   name: test
   state: absent
