---
# Role tasks

- block:
    - name: Install mysql community repository package
      yum:
        name: "{{ mysql_repo_package_url }}"
        state: present
        disable_gpg_check: yes

    - name: Disable all mysql releases repositories
      replace:
        path: "{{ mysql_repo_file_path }}"
        regexp: "enabled *= *1"
        replace: "enabled=0"

    - name: Disable package manager mysql module
      command: yum -y module disable mysql
      args:
        warn: no
      when: ansible_facts.distribution_major_version is version("7", ">")
      register: mysql_disable_module_result
      changed_when: >-
        mysql_disable_module_result.stdout is not search("Nothing to do")
      environment:
        LANG: en_US

    - name: Install selected mysql version
      yum:
        name: "{{ package }}"
        state: present
        enablerepo: "mysql{{ mysql_release }}-community"
        disable_gpg_check: "{{ mysql_disable_gpg_check | bool }}"
      loop: "{{ mysql_packages }}"
      loop_control:
        loop_var: package

    - name: Start mysql service with defaults
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Setup extra directories
      file:
        path: "{{ mysql_extra_dir }}"
        state: directory
        owner: "{{ mysql_user }}"
        group: "{{ mysql_group }}"
        mode: "0755"
        seuser: system_u
        serole: object_r
        setype: mysqld_db_t
        selevel: s0
      loop:
        - "{{ mysql_innodb_temp_dir }}"
        - "{{ mysql_binlog_dir }}"
      loop_control:
        loop_var: mysql_extra_dir

    - name: Setup log directory
      file:
        path: "{{ mysql_log_dir }}"
        state: directory
        owner: "{{ mysql_user }}"
        group: "{{ mysql_group }}"
        mode: "0755"
        seuser: system_u
        serole: object_r
        setype: mysqld_log_t
        selevel: s0

    - name: Setup mysql configuration file
      template:
        src: my.cnf.j2
        dest: "{{ mysql_config_file_path }}"
        mode: "0644"
      register: mysql_setup_my_cnf_result

    - include_tasks: limits.yml
      when:
        - mysql_setup_my_cnf_result is changed
        - mysql_adjust_limits

    - name: Restart mysql service to apply settings
      service:
        name: mysqld
        state: restarted
        enabled: yes
      when: mysql_setup_my_cnf_result is changed
  environment: "{{ proxy_client_environment }}"
