---
# Role tasks

- block:
    - include_tasks: encrypt.yml
      when:
        - mysql_encrypted_password | bool
      tags:
        - role::mysql::encrypt

    - include_tasks: install.yml
      tags:
        - role::mysql::install

    - include_tasks: configure.yml
      tags:
        - role::mysql::configure

    - include_tasks: replication.yml
      when:
        - mysql_replication | bool
        - mysql_server_id | int > 1
      tags:
        - role::mysql::replication

    - include_tasks: cleanup.yml
      tags:
        - role::mysql::cleanup
  tags:
    - role::mysql
