---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: vagrant
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/8
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 3072
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    box: fedora/34-cloud-base
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          mysql_root_user: root
          mysql_root_password: t3stp4ssw0rd
          mysql_no_log: no
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
      molecule_hosts_centos_7:
        vars:
          mysql_version: 8.0
      molecule_hosts_centos_8:
        vars:
          mysql_version: 8.0
      molecule_hosts_fedora_33:
        vars:
          mysql_version: 8.0
      molecule_hosts_fedora_34:
        vars:
          mysql_version: 8.0
verifier:
  name: ansible
