---

dependency:
  name: galaxy
driver:
  name: vagrant
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/8
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora32-${INSTANCE_UUID:-1}"
    box: fedora/32-cloud-base
    memory: 3072
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_become: yes
          ansible_become_user: root
          ansible_become_pass: vagrant
          mysql_root_user: root
          mysql_root_password: t3stp4ssw0rd
          mysql_no_log: no
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
      molecule_hosts_centos_7:
        vars:
          mysql_version: 8.0
      molecule_hosts_centos_8:
        vars:
          mysql_version: 8.0
      molecule_hosts_fedora_32:
        vars:
          mysql_version: 8.0
      molecule_hosts_fedora_33:
        vars:
          mysql_version: 8.0
verifier:
  name: ansible
