---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Get mysql info
      mysql_info:
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        filter:
          - version
      register: mysql_read_info

    - name: Make sure version installed is correct
      assert:
        that:
          - mysql_read_info.version.major == 5
          - mysql_read_info.version.minor == 7

    - name: Test root user autologin
      shell: 'mysql -e "show databases;"'
      register: mysql_read_autologin_test

    - name: Assert root user can access without password locally
      assert:
        that:
          - mysql_read_autologin_test.stdout is search("mysql")
          - mysql_read_autologin_test.stdout is search("information_schema")
          - mysql_read_autologin_test.stdout is search("performance_schema")
