---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Gather mysql info
      mysql_info:
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        filter:
          - version
      register: mysql_read_info

    - name: Assert version installed is correct
      ansible.builtin.assert:
        that:
          - >-
            mysql_read_info.version.major | string
            == (mysql_version | string).split(".")[0]
          - >-
            mysql_read_info.version.minor | string
            == (mysql_version | string).split(".")[1]

    - name: Test root user autologin
      ansible.builtin.shell: 'mysql -e "show databases;"'
      changed_when: no
      register: mysql_autologin_result

    - name: Assert root user can access locally without password
      ansible.builtin.assert:
        that:
          - mysql_autologin_result.stdout is search("mysql")
          - mysql_autologin_result.stdout is search("information_schema")
          - mysql_autologin_result.stdout is search("performance_schema")