---

dependency:
  name: galaxy
driver:
  name: vagrant
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/8
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora32-${INSTANCE_UUID:-1}"
    box: fedora/32-cloud-base
    memory: 3072
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    host_vars:
      mysql-master:
        mysql_server_id: "1"
      mysql-slave:
        mysql_server_id: "2"
        mysql_replication_master: mysql-master
        mysql_replication_master_port: 3306
    group_vars:
      molecule_hosts:
        mysql_version: 8.0
        mysql_replication: yes
        mysql_root_user: root
        mysql_root_password: t3stp4ssw0rd
        mysql_root_allowed_hosts:
          - localhost
        mysql_no_log: no
verifier:
  name: ansible
