---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "mysql-master"
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "mysql-slave"
    image: centos:7
    command: /sbin/init
    etc_hosts: "{'mysql-master': '172.17.0.2'}"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    host_vars:
      mysql-master:
        mysql_server_id: "1"
      mysql-slave:
        mysql_server_id: "2"
        mysql_replication_master: mysql-master
        mysql_replication_master_port: 3306
    group_vars:
      molecule_hosts:
          mysql_version: 5.7.18
          mysql_replication: yes
          mysql_root_user: root
          mysql_root_password: t3stp4ssw0rd
          mysql_root_allowed_hosts:
            - localhost
          mysql_no_log: no
verifier:
  name: ansible
