---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Added entries to /etc/hosts
      ansible.builtin.shell: >-
        echo \
        {{ hostvars[primary_host].ansible_facts.default_ipv4.address }} \
        {{ primary_host }} \
        > /etc/hosts
      args:
        warn: no
      when: inventory_hostname in groups.molecule_hosts_mysql_replica
      vars:
        primary_host: "{{ groups.molecule_hosts_mysql_primary.0 }}"