---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Verify replica
      block:
        - name: Get replica status
          mysql_replication:
            mode: getreplica
            login_user: "{{ mysql_root_user }}"
            login_password: "{{ mysql_root_password }}"
          register: mysql_verify_replication

        - name: Make sure replication is working
          ansible.builtin.assert:
            that:
              - mysql_verify_replication.Replica_IO_Running == "Yes"
              - mysql_verify_replication.Replica_SQL_Running == "Yes"
              - mysql_verify_replication.Seconds_Behind_Source == 0
              - >-
                mysql_verify_replication.Replica_IO_State
                is search("Waiting for")
              - >-
                mysql_verify_replication.Replica_SQL_Running_State
                is search("read all relay log")
      when: mysql_server_id | int > 1